layout: default
title: Tiago Souza
logo: /assets/img/logo.png
description: Articles and references about Java, Python, Javascript and AWS.
tagline: 'Tiago Souza'
url: "https://metiago.github.io/"


plugins: [jekyll-seo-tag, jekyll-paginate-v2, jekyll-watch, jekyll-sitemap]

whitelist:
  - jekyll-paginate-v2
  - jekyll-sitemap