title: 
logo: /assets/img/logo.png
# description: A simple blog about programming
show_downloads: false

plugins: [jekyll-seo-tag, jekyll-paginate-v2, jekyll-watch]

# Pagination Settings
pagination:
  enabled: true
  per_page: 3
  offset: 2
  permalink: '/page/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

whitelist:
  - jekyll-paginate-v2