baseURL = 'https://example.org/'
languageCode = 'en-EN'
title = 'Old Trunk'
theme = ["hyde"]
enableInlineShortcodes = true
enableRobotsTXT = true
summaryLength = 8
[params]
  description = "just experiments"
  commentoEnable = false
  disqusShortname = ''
  text_color = "#FFF"
  author = ""
  favicon = ""
  site_logo = ""
  background_color_class = "bg-black"
  recent_posts_number = 6
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5