site_name: Reticência
site_url: https://example.com/
nav:
  - Home: index.md
  - About: about.md
  - DS&A:
    - Big O: big-o.md
    - Balanced Brackets: balanced-brackets.md
    - Binary Search Tree: binary-search-tree.md
    - Doubly Linked Lists: doubly-linked-lists.md
    - Fibonacci: fibonacci.md
    - Graph: graphs.md
    - Java Binary Search: java-binary-search.md
    - Java Bubble Sort: java-bubble-sort.md
    - Java Date & Time: java-date-datetime.md
    - Java Hash Tables: java-hashtable.md
    - Java Insertion Sort: java-insertion-sort.md
    - Java Linear Search: java-linear-search.md
    - Java Merge Sort: java-merge-sort.md
    - Java Queues: java-queue.md
    - Java Quick Sort: java-quick-sort.md
    - Java Regex: java-regex.md
    - Java Selection Sort: java-selection-sort.md
    - Java Stacks: java-stack.md
    - Java Tree: java-tree.md
    - Java Linked Lists: linked-lists.md
  - Strings:
    - Java Strings: strings/java-strings.md
  - Functional:
    - Java Optional: functional/java-optional.md
    - Java Streams: functional/java-streams.md
  - Collections & Maps:
    - Collections & Maps: functional/java-maps-collections.md
  - Testing:
    - AAA: tests.md
  
theme:
  name: mkdocs
  locale: en

extra_css:
    - css/reticencia.css